---
output: 
  html_document: default
editor_options:
  chunk_output_type: console
params:
  set_title_1: !r first_date
  set_title_2: !r last_date
---

---
title: WWRG tagged curlew movements *by time of day* from `r params$set_title_1` to `r params$set_title_2`
---

```{css, echo=FALSE}
body .main-container {
  max-width: 1600px;
  height: 1200px;
}
body {
  max-width: 1600px;
  height: 1200px;
  font-size: 12px;
}
h1.title {
  font-size: 24px;
}
h1 { /* Header 1 */
    font-size: 16px;
}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.height = 8, out.width="100%")
```


```{r leaflet-map-by-time, results='hide', eval = TRUE}

# filter out wonky flight heights
# convert lat lon to points
dt_map <- st_as_sf(tags_cleaned, coords = c("location_long","location_lat"), crs=4326)

## Create a continuous palette function
# pal <- colorNumeric(
#   palette = "YlGnBu",
#   domain = dt_map$sec_since_midnight)

factpal <- colorFactor(palette = "Blues", dt_map$day_night)


# create base map
leaflet_map <- leaflet(options = leafletOptions(
  zoomSnap = 0.5,
  zoomDelta = 0.5
)) %>% 
  addProviderTiles("CartoDB.PositronNoLabels", group = "CartoDB Positron")  %>%
  addProviderTiles("CartoDB.Positron", group = "CartoDB Positron with labels")  %>%
  addProviderTiles("CartoDB.DarkMatterNoLabels", group="CartoDB Dark Matter") %>%
  addProviderTiles("Esri.WorldImagery", group = "Esri WorldImagery") %>%
  addTiles(group = "OpenStreetMap")


leaflet_map <- leaflet_map %>%
    addCircleMarkers(data = dt_map,
                     fill = TRUE,
                     radius = 1,
                     fillColor = ~factpal(day_night),
                     fillOpacity = 0.8,
                     stroke = TRUE,
                     color = ~factpal(day_night),
                     label = ~new_datetime_min,
                     options = popupOptions(closeButton = TRUE)
    )


# add extra controls for layers, legends, etc
leaflet_map <- leaflet_map %>% 
  addLayersControl(
    baseGroups = c("CartoDB Positron", "CartoDB Positron with labels", "CartoDB Dark Matter", "Esri WorldImagery", "OpenStreetMap")
  ) %>%
addLegend("bottomleft", pal = factpal, values = dt_map$day_night,
    title = "Day / night (where Day = 06:00-18:00 UTC)",
    opacity = 1
  )

```


```{r output-leaflet-map, eval = TRUE, fig.width = 12}
leaflet_map

```